name: Documentation

on:
  pull_request:
    paths:
      - ".github/workflows/docs-check.yml"
      - ".github/workflows/docs-deploy.yml"
      - "docs/**"
      - "requirements-docs.txt"
      - "zensical.toml"
  push:
    branches: [main]
    paths:
      - ".github/workflows/docs-check.yml"
      - ".github/workflows/docs-deploy.yml"
      - "docs/**"
      - "requirements-docs.txt"
      - "zensical.toml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install documentation dependencies
        run: pip install --requirement requirements-docs.txt
      - name: Build documentation
        run: zensical build --clean --strict
